- "get":
    "key": "actors"
    "permission": "get:actors"
- "get":
    "key": "movies"
    "permission": "get:movies"
- "post":
    "key": "actor"
    "permission": "post:actors"
- "post":
    "key": "movie"
    "permission": "post:movies"
- "patch":
    "key": "actor"
    "permission": "patch:actors"
- "patch":
    "key": "movie"
    "permission": "patch:movies"
- "delete":
    "key": "actor"
    "permission": "delete:actors"
- "delete":
    "key": "movie"
    "permission": "delete:movies"
